objects/Abandoned_Checkout__c/Abandoned_Checkout__c.object-meta.xml
<CustomObject>
    <label>Abandoned Checkout</label>
    <nameField>
        <displayFormat>ABCT-{0000}</displayFormat>
        <label>Abandoned Checkout Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Abandoned Checkouts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Abandoned_Checkout__c/fields/AbandonedCheckoutUrl__c.field-meta.xml
<CustomField>
    <fullName>AbandonedCheckoutUrl__c</fullName>
    <label>AbandonedCheckoutUrl</label>
    <type>Url</type>
</CustomField>

objects/Abandoned_Checkout__c/fields/customerid__c.field-meta.xml
<CustomField>
    <fullName>customerid__c</fullName>
    <label>Customer Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/Abandoned_Checkout__c/fields/full_name__c.field-meta.xml
<CustomField>
    <fullName>full_name__c</fullName>
    <label>Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/Abandoned_Checkout__c/fields/latest_abandonment__c.field-meta.xml
<CustomField>
    <fullName>latest_abandonment__c</fullName>
    <label>Latest Abandonment</label>
    <type>DateTime</type>
</CustomField>

objects/Abandoned_Checkout__c/fields/phone__c.field-meta.xml
<CustomField>
    <fullName>phone__c</fullName>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

classes/InvocableGetAbandonedCheckouts.cls
global class InvocableGetAbandonedCheckouts{
    @InvocableMethod(label = 'Returns the List of Abandoned Checkouts')
    global static List<Output> handleSlackCheckout(List<Input> inputs){
        List<Output> ops = new List<Output>();
        Output op = new Output();
        
         // Step 1: Fetch more records for deduplication
            List<Abandoned_Checkout__c> rawCheckouts = [
                SELECT full_name__c, email__c, phone__c,AbandonedCheckoutUrl__c, latest_abandonment__c,customerid__c
                FROM Abandoned_Checkout__c
                WHERE email__c != null AND email__c != ''
                ORDER BY latest_abandonment__c DESC
                LIMIT 100
            ];
            
            // Step 2: Deduplicate based on email__c
            Map<String, Abandoned_Checkout__c> uniqueEmailMap = new Map<String, Abandoned_Checkout__c>();
            for (Abandoned_Checkout__c record : rawCheckouts) {
                if (!uniqueEmailMap.containsKey(record.email__c)) {
                    uniqueEmailMap.put(record.email__c, record);
                }
            }

        // Step 3: Store deduplicated list
        List<Abandoned_Checkout__c> abandonedCheckouts = new List<Abandoned_Checkout__c>();
        abandonedCheckouts.addAll(uniqueEmailMap.values());


        op.res = abandonedCheckouts;
        ops.add(op);
        return ops;
    }

    global class Input{
        @InvocableVariable
        public String req;
    }

    global class Output{
        @InvocableVariable
        public List<Abandoned_Checkout__c> res;

    }

}